# Generated by Django 2.1 on 2018-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0005_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('zonemap', models.ImageField(upload_to='zonemap/')),
                ('dos', models.TextField(blank=True)),
            ],
        ),
    ]
